import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, Check, ChefHat, ClipboardList, Clock3, CookingPot, PackageOpen, Power, Plus, Scale, ShoppingBasket, X } from "lucide-react";
import { useState, type FormEvent } from "react";
import { useSearchParams } from "react-router-dom";
import { JalaliDatePicker } from "../components/JalaliDatePicker";
import { RecipeEditor } from "../components/RecipeEditor";
import { Badge, Button, EmptyState, Modal, Spinner } from "../components/ui";
import { useAuth } from "../context/AuthContext";
import { ApiError, api } from "../lib/api";
import { businessDate, dateOnly, money, quantity, statusLabel, timeOnly } from "../lib/format";
import type {
  KitchenInventoryItem,
  KitchenMenuItem,
  KitchenOrder,
  Recipe,
  SystemSettings,
  User,
} from "../types";

interface DailyNeed { id: number; required_date: string; inventory_item_id: number | null; item_name: string; quantity: string; unit: string; priority: "low" | "normal" | "high" | "urgent"; source: "manual" | "automatic"; status: "pending" | "approved" | "rejected" | "fulfilled" | "cancelled"; notes: string | null; requested_by: User; created_at: string }

export default function KitchenPage() {
  const { user } = useAuth();
  const client = useQueryClient();
  const [params] = useSearchParams();
  const [tab, setTab] = useState<"queue" | "recipes" | "needs">(params.get("tab") === "needs" ? "needs" : "queue");
  const [recipeModal, setRecipeModal] = useState<Recipe | "new" | null>(null);
  const [needModal, setNeedModal] = useState(false);
  const [error, setError] = useState("");
  const recipes = useQuery({ queryKey: ["recipes"], queryFn: () => api<Recipe[]>("/kitchen/recipes") });
  const needs = useQuery({ queryKey: ["daily-needs"], queryFn: () => api<DailyNeed[]>("/kitchen/daily-needs") });
  const orders = useQuery({ queryKey: ["kitchen-orders"], queryFn: () => api<KitchenOrder[]>("/kitchen/orders"), refetchInterval: 12_000 });
  const systemSettings = useQuery({ queryKey: ["system-settings"], queryFn: () => api<SystemSettings>("/settings"), refetchInterval: 30_000 });
  const menu = useQuery({ queryKey: ["kitchen-menu-items"], queryFn: () => api<KitchenMenuItem[]>("/kitchen/menu-items") });
  const inventory = useQuery({ queryKey: ["kitchen-inventory-items"], queryFn: () => api<KitchenInventoryItem[]>("/kitchen/inventory-items") });
  const invalidate = () => { client.invalidateQueries({ queryKey: ["recipes"] }); client.invalidateQueries({ queryKey: ["daily-needs"] }); client.invalidateQueries({ queryKey: ["kitchen-orders"] }); client.invalidateQueries({ queryKey: ["dashboard"] }); };
  const mutation = useMutation({
    mutationFn: ({ path, method, body }: { path: string; method: string; body?: object }) => api(path, { method, body }),
    onSuccess: () => { invalidate(); setRecipeModal(null); setNeedModal(false); setError(""); },
    onError: (reason) => setError(reason instanceof ApiError ? reason.message : "انجام عملیات ممکن نشد"),
  });
  const kitchenWorkflowEnabled = systemSettings.data?.kitchen_workflow_enabled !== false;
  const queue = kitchenWorkflowEnabled ? orders.data?.filter((order) => ["confirmed", "preparing", "ready"].includes(order.status)) || [] : [];

  const decideNeed = (id: number, status: "approved" | "rejected") => mutation.mutate({ path: `/kitchen/daily-needs/${id}/decision`, method: "POST", body: { status } });
  const statusOrder = (id: number, status: string) => mutation.mutate({ path: `/orders/${id}/status`, method: "PATCH", body: { status } });
  const saveNeed = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const selected = inventory.data?.find((item) => item.id === Number(form.get("inventory_item_id"))); mutation.mutate({ path: "/kitchen/daily-needs", method: "POST", body: { required_date: form.get("required_date"), inventory_item_id: selected?.id || null, item_name: selected?.name || form.get("item_name"), quantity: form.get("quantity"), unit: form.get("unit"), priority: form.get("priority"), notes: form.get("notes") || null } }); };

  return (
    <div className="page-stack">
      <header className="page-heading"><div><span className="eyebrow">عملیات آشپزخانه</span><h1>مدیریت آشپزخانه</h1><p>فیش‌های زنده، دستور پخت دقیق، هزینه واقعی و برنامه خرید روز آینده.</p></div>{tab === "recipes" ? <Button onClick={() => { setError(""); setRecipeModal("new"); }}><Plus size={18} /> دستور پخت جدید</Button> : tab === "needs" ? <Button onClick={() => { setError(""); setNeedModal(true); }}><Plus size={18} /> افزودن نیاز</Button> : null}</header>
      <div className="tabs"><button className={tab === "queue" ? "active" : ""} onClick={() => setTab("queue")}>آشپزخانه زنده <span>{queue.length}</span></button><button className={tab === "recipes" ? "active" : ""} onClick={() => setTab("recipes")}>دستورهای پخت</button><button className={tab === "needs" ? "active" : ""} onClick={() => setTab("needs")}>نیازهای روزانه <span>{needs.data?.filter((need) => need.status === "pending").length || 0}</span></button></div>

      {tab === "queue" && <section className="kitchen-board">{orders.isLoading || systemSettings.isLoading ? <div className="center-loader"><Spinner /></div> : !kitchenWorkflowEnabled ? <div className="panel kitchen-workflow-off"><span><Power /></span><div><h2>حالت گردش آشپزخانه غیرفعال است</h2><p>سفارش‌ها در صندوق همان لحظه پذیرفته و تکمیل می‌شوند؛ بنابراین صف سه‌مرحله‌ای نمایش داده نمی‌شود.</p><small>دستورهای پخت و نیازهای خرید همچنان فعال‌اند. مدیر ریشه می‌تواند این حالت را از داشبورد اصلی دوباره روشن کند.</small></div></div> : queue.length ? ["confirmed", "preparing", "ready"].map((status) => <div className={`kitchen-column kitchen-${status}`} key={status}><header><span>{status === "confirmed" ? <ClipboardList /> : status === "preparing" ? <CookingPot /> : <Check />}</span><div><h2>{status === "confirmed" ? "سفارش‌های جدید" : status === "preparing" ? "در حال آماده‌سازی" : "آماده تحویل"}</h2><small>{quantity(queue.filter((order) => order.status === status).length)} سفارش</small></div></header><div>{queue.filter((order) => order.status === status).map((order) => <article className={`kitchen-ticket ${order.is_staff_meal ? "staff-kitchen-ticket" : ""} ${order.order_type === "takeaway" ? "takeaway-kitchen-ticket" : ""}`} key={order.id}><div className="ticket-head"><strong>{order.order_number}</strong><span><Clock3 size={14} /> {timeOnly(order.created_at)}</span></div><div className="kitchen-customer"><h3>{order.customer_name === "Guest" ? "مهمان" : order.customer_name}</h3><div className="kitchen-order-badges">{order.order_type === "takeaway" && <Badge tone="warning"><PackageOpen size={13} /> بیرون‌بر · {quantity(order.takeaway_package_count)} بسته</Badge>}{order.is_staff_meal && <Badge tone="violet">غذای پرسنلی</Badge>}</div></div><div className="ticket-lines">{order.items.map((item) => <div key={item.id}><b>{quantity(item.quantity)}×</b><span>{item.name}{item.notes && <em>{item.notes}</em>}</span></div>)}</div>{order.notes && <div className="ticket-note">{order.notes}</div>}<Button onClick={() => statusOrder(order.id, status === "confirmed" ? "preparing" : status === "preparing" ? "ready" : "completed")}>{status === "confirmed" ? "شروع آماده‌سازی" : status === "preparing" ? "اعلام آماده تحویل" : "تکمیل سفارش"}</Button></article>)}</div></div>) : <div className="panel"><EmptyState icon={<ChefHat />} title="صف آشپزخانه خالی است" text="سفارش‌های جدید به‌صورت خودکار اینجا نمایش داده می‌شوند." /></div>}</section>}

      {tab === "recipes" && <section className="panel recipe-panel">{recipes.isLoading ? <div className="center-loader"><Spinner /></div> : recipes.data?.length ? <div className="recipe-grid">{recipes.data.map((recipe) => <article className="recipe-card" key={recipe.id}><div className="recipe-accent"><ChefHat /></div><div className="recipe-head"><div><h3>{recipe.menu_item.name}</h3><span>{recipe.menu_item.category} · خروجی {quantity(recipe.yield_quantity)}</span></div><Badge tone="info">فرمول دقیق مصرف</Badge></div><div className="recipe-metrics"><span><Scale size={17} /><div><small>هزینه مواد هر پرس</small><strong>{money(recipe.calculated_cost)}</strong></div></span><span><Clock3 size={17} /><div><small>زمان آماده‌سازی</small><strong>{quantity(recipe.preparation_minutes)} دقیقه</strong></div></span></div><div className="ingredient-preview">{recipe.ingredients.slice(0, 4).map((line) => <span key={line.inventory_item_id}>{line.inventory_item?.name}<b>{quantity(line.quantity)} {line.unit}</b></span>)}{recipe.ingredients.length > 4 && <small>+ {quantity(recipe.ingredients.length - 4)} ماده دیگر</small>}</div><Button variant="secondary" onClick={() => { setError(""); setRecipeModal(recipe); }}>مشاهده دستور</Button></article>)}</div> : <EmptyState icon={<CookingPot />} title="هنوز دستور پختی ثبت نشده" text="برای محاسبه هزینه و کسر خودکار موجودی، مواد اولیه را دقیق ثبت کنید." />}</section>}

      {tab === "needs" && <section className="panel needs-panel"><header className="panel-header"><div><h2>فهرست خرید فردا</h2><p>درخواست دستی آشپزخانه و پیشنهاد خودکار انبار، با منبع و محاسبه کاملاً شفاف.</p></div></header>{needs.isLoading ? <div className="center-loader"><Spinner /></div> : needs.data?.length ? <div className="needs-list">{needs.data.map((need) => <article key={need.id} className={need.source === "automatic" ? "automatic-need" : ""}><div className={`priority-mark priority-${need.priority}`} /><div className="need-date"><CalendarDays size={18} /><span><strong>{dateOnly(need.required_date, { weekday: "short", month: "short", day: "numeric" })}</strong><small>اولویت {statusLabel[need.priority]}</small></span></div><div className="need-main"><div className="need-title"><strong>{need.item_name}</strong><Badge tone={need.source === "automatic" ? "info" : "neutral"}>{need.source === "automatic" ? "پیشنهاد خودکار انبار" : "درخواست دستی آشپزخانه"}</Badge></div><small>{quantity(need.quantity)} {need.unit} · {need.source === "automatic" ? "محاسبه سیستم" : `درخواست ${need.requested_by.full_name}`}</small>{need.notes && <p>{need.notes}</p>}</div><Badge tone={["approved", "fulfilled"].includes(need.status) ? "success" : ["rejected", "cancelled"].includes(need.status) ? "danger" : "warning"}>{statusLabel[need.status]}</Badge>{user?.role === "root" && need.status === "pending" && <div className="approval-actions"><button title="تأیید" className="approve" onClick={() => decideNeed(need.id, "approved")}><Check size={17} /></button><button title="رد" className="reject" onClick={() => decideNeed(need.id, "rejected")}><X size={17} /></button></div>}</article>)}</div> : <EmptyState icon={<ShoppingBasket />} title="نیاز خریدی ثبت نشده" text="درخواست دستی آشپزخانه یا هشدار خودکار موجودی اینجا نمایش داده می‌شود." />}</section>}

      <RecipeEditor open={recipeModal !== null} recipe={recipeModal && recipeModal !== "new" ? recipeModal : null} close={() => setRecipeModal(null)} menu={menu.data || []} inventory={inventory.data || []} save={(body, id) => mutation.mutate({ path: id ? `/kitchen/recipes/${id}` : "/kitchen/recipes", method: id ? "PUT" : "POST", body })} pending={mutation.isPending} error={error} />
      <Modal open={needModal} title="افزودن نیاز خرید روزانه" onClose={() => setNeedModal(false)}><form className="form-grid" onSubmit={saveNeed}><label className="field"><span>تاریخ نیاز</span><JalaliDatePicker name="required_date" min={businessDate()} defaultValue={businessDate(1)} required ariaLabel="تاریخ شمسی نیاز خرید" /></label><label className="field"><span>اولویت</span><select name="priority" defaultValue="normal"><option value="low">کم</option><option value="normal">عادی</option><option value="high">زیاد</option><option value="urgent">فوری</option></select></label><label className="field field-wide"><span>کالای موجود در انبار <small>(اختیاری)</small></span><select name="inventory_item_id" defaultValue=""><option value="">نام کالای سفارشی را پایین بنویسید</option>{inventory.data?.map((item) => <option key={item.id} value={item.id}>{item.name} · موجودی {quantity(item.current_quantity)} {item.unit}</option>)}</select></label><label className="field field-wide"><span>نام کالا</span><input name="item_name" placeholder="برای کالای سفارشی الزامی است" /></label><label className="field"><span>مقدار</span><input name="quantity" type="number" min="0.001" step="0.001" required /></label><label className="field"><span>واحد</span><input name="unit" required placeholder="کیلوگرم، بطری، بسته…" /></label><label className="field field-wide"><span>توضیحات</span><textarea name="notes" rows={3} placeholder="جزئیات کیفیت، تأمین‌کننده یا زمان تحویل…" /></label>{error && <div className="form-error field-wide">{error}</div>}<div className="form-actions field-wide"><Button type="button" variant="secondary" onClick={() => setNeedModal(false)}>انصراف</Button><Button type="submit" disabled={mutation.isPending}>ارسال درخواست</Button></div></form></Modal>
    </div>
  );
}
